server:
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/converter?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true
  thymeleaf:
    cache: false